site_name: msamtools
site_description: Microbiome-related extension to samtools

nav:
  - Home: index.md
  - Installation: installation.md
  - Input requirements: input-requirements.md
  - Compatibility: compatibility.md
  - Examples: examples.md
  - Commands:
      - filter: filter.md
      - profile: profile.md
      - coverage: coverage.md
      - summary: summary.md
  - Validation:
      - Profile validation: validation/profile_validation.md
