#!/usr/bin/env python3
"""Generate a deterministic synthetic paired-end SAM dataset for msamtools validation.

This script is the second stage of the reproducible msamtools validation-data
workflow. It consumes chromosome-only genomes prepared by ``prepare_genomes.py``
and generates a realistic but controlled metagenomic alignment dataset for
Tier-2 validation of msamtools abundance profiling.

The simulator works directly in alignment space; it does NOT call a read mapper.
This is intentional. Exact source and alternative alignments are known by
construction, allowing the resulting SAM file to have fully traceable ground
truth without introducing mapper-specific heuristics.

Simulation model
----------------
* Paired-end reads: 2 x 100 bp.
* Insert length: 175 bp (25 bp mate overlap).
* Alignments use CIGAR ``100M`` only.
* Each mate independently receives 0, 1, 2, or 3 substitutions.
* Source genomes are sampled proportional to:
      true cell abundance x chromosome length
  so length-normalized profiling can be compared with the known cell abundance.
* Exact multi-mappers are identified from genuine identical 175-bp chromosome
  segments. Candidate inserts are sampled first, then all chromosomes are
  scanned once with a rolling 2-bit encoder to find exact occurrences.
* A configurable fraction of inserts is deliberately drawn from shared loci to
  ensure that multi-mapper handling receives adequate validation coverage.
* A configurable fraction of inserts contains only one mapped mate. These
  inserts are emitted with a single mapped SAM record so that profiling in
  insert space is represented in the validation data.
* SAM records are grouped by QNAME, as required by msamtools ``profile``.

This script deliberately does NOT test clipping, indels, malformed/missing SAM
tags, unmapped-read handling, threshold boundaries, coordinate-sort rejection,
or other exact CLI/error semantics. Those belong to the Tier-1 test suite.

Usage
-----
Typical use::

    python3 generate_synthetic_alignments.py \
        prepared_genomes/validated_genomes.tsv \
        community_abundances.tsv

Choose the number of simulated inserts and random seed::

    python3 generate_synthetic_alignments.py \
        prepared_genomes/validated_genomes.tsv \
        community_abundances.tsv \
        --num-inserts 10000 \
        --seed 13579

Change the deliberately enriched shared-locus fraction::

    python3 generate_synthetic_alignments.py \
        prepared_genomes/validated_genomes.tsv \
        community_abundances.tsv \
        --shared-fraction 0.20

Change mismatch-class probabilities::

    python3 generate_synthetic_alignments.py \
        prepared_genomes/validated_genomes.tsv \
        community_abundances.tsv \
        --mismatch-weights 0:0.50,1:0.30,2:0.10,3:0.10

Exclude repeats confined to a single genome while retaining cross-genome
multi-mappers::

    python3 generate_synthetic_alignments.py \
        prepared_genomes/validated_genomes.tsv \
        community_abundances.tsv \
        --exclude-within-genome-repeats

Exclude all cross-genome multimappers for a strict no-sharing control::

    python3 generate_synthetic_alignments.py \
        prepared_genomes/validated_genomes.tsv \
        community_abundances.tsv \
        --shared-fraction 0 \
        --exclude-cross-genome-multimappers

Input: validated_genomes.tsv
----------------------------
The validation report produced by ``prepare_genomes.py``. Required columns are::

    assembly_accession
    expected_species
    expected_strain
    chromosome_accession
    chromosome_length
    fasta_path
    status

Only rows with ``status=PASS`` are accepted.

Input: community_abundances.tsv
-------------------------------
A tab-separated file with::

    assembly_accession    relative_abundance

Abundances must be positive and sum to 1 within a small numerical tolerance.
Every validated genome must occur exactly once.

Outputs
-------
By default, ``synthetic_validation/`` contains:

``alignments.sam``
    QNAME-grouped paired-end SAM suitable for msamtools profiling.
``community_truth.tsv``
    Cell abundance, chromosome length, DNA fraction, and realized source counts.
``insert_sources.tsv``
    Minimal per-insert source truth: QNAME, source assembly, and mate status.
``reference_metadata.tsv``
    Reference, assembly, species, strain, and safe feature identifiers.
``reference_to_species.tsv``
    Two-column msamtools genome-definition file collapsing strains to species.
``reference_to_strain.tsv``
    Two-column msamtools genome-definition file retaining strain-level features.
``multimapping_pairs.tsv``
    Counts of cross-genome ambiguous inserts for each target-genome pair.
``simulation_summary.tsv``
    Machine-readable key/value summary of the realized dataset, including
    single-locus, same-genome-repeat, and cross-genome ambiguity classes.

Requirements
------------
* Python 3.9 or newer.
* No third-party Python packages.
* Chromosome FASTAs generated by ``prepare_genomes.py``.

Reproducibility notes
---------------------
All random choices use a dedicated ``random.Random`` instance seeded by
``--seed``. Sets and mappings are sorted before randomized selection or output
where ordering could otherwise depend on hash iteration order.

The exact-matching index is deliberately query-driven rather than genome-wide:
candidate inserts are sampled first, their 175-bp sequences are encoded, and
the chromosomes are then scanned with a rolling 2-bit representation. This
keeps memory use proportional to the candidate pool instead of storing tens of
millions of genome-wide k-mers.
"""

from __future__ import annotations

import argparse
import csv
import math
import random
import re
import sys
from collections import Counter, defaultdict
from itertools import combinations
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Iterator, Sequence


READ_LENGTH = 100
INSERT_LENGTH = 175
MATE_OFFSET = INSERT_LENGTH - READ_LENGTH  # 75 bp
DEFAULT_MISMATCH_WEIGHTS = "0:0.50,1:0.30,2:0.10,3:0.10"
DNA_BASES = "ACGT"
COMPLEMENT = str.maketrans("ACGT", "TGCA")

REQUIRED_GENOME_COLUMNS = {
    "assembly_accession",
    "expected_species",
    "expected_strain",
    "chromosome_accession",
    "chromosome_length",
    "fasta_path",
    "status",
}
REQUIRED_ABUNDANCE_COLUMNS = {"assembly_accession", "relative_abundance"}


@dataclass(frozen=True)
class Genome:
    """One validated chromosome used as a simulation reference."""

    assembly_accession: str
    species: str
    strain: str
    chromosome_accession: str
    sequence: str
    fasta_path: Path

    @property
    def length(self) -> int:
        """Return chromosome length in bases."""

        return len(self.sequence)


@dataclass(frozen=True)
class Occurrence:
    """One exact occurrence of a candidate insert in a reference chromosome."""

    assembly_accession: str
    start: int  # zero-based leftmost coordinate on the reference
    orientation: str  # '+' if candidate sequence matches reference, '-' if RC matches


@dataclass(frozen=True)
class Candidate:
    """One candidate source insert sampled before final dataset selection."""

    source_assembly: str
    source_start: int
    fragment_code: int


@dataclass
class SelectedInsert:
    """A finalized insert and its exact reference occurrences."""

    qname: str
    source_assembly: str
    source_start: int
    fragment_code: int
    occurrences: list[Occurrence]
    selection_mode: str
    mate_status: str = "both_mapped"
    mate1_nm: int = 0
    mate2_nm: int = 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "Generate deterministic 2x100-bp paired-end synthetic SAM data "
            "from validated bacterial chromosomes for msamtools profiling validation."
        )
    )
    parser.add_argument(
        "validated_genomes",
        type=Path,
        help="validated_genomes.tsv produced by prepare_genomes.py",
    )
    parser.add_argument(
        "abundances",
        type=Path,
        help="TSV with assembly_accession and relative_abundance columns",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("synthetic_validation"),
        help="output directory (default: synthetic_validation)",
    )
    parser.add_argument(
        "--num-inserts",
        type=int,
        default=10000,
        help="number of biological inserts to simulate (default: 10000)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=13579,
        help="random seed (default: 13579)",
    )
    parser.add_argument(
        "--shared-fraction",
        type=float,
        default=0.20,
        help=(
            "target fraction of each genome's inserts deliberately selected from "
            "cross-genome identical 175-bp loci when available (default: 0.20)"
        ),
    )
    parser.add_argument(
        "--single-mate-fraction",
        type=float,
        default=0.05,
        help=(
            "fraction of inserts emitted with only one mapped mate; these are "
            "selected from non-shared candidates when possible (default: 0.05)"
        ),
    )
    parser.add_argument(
        "--candidate-multiplier",
        type=float,
        default=5.0,
        help=(
            "candidate inserts sampled per required final insert before shared-locus "
            "selection (default: 5.0)"
        ),
    )
    parser.add_argument(
        "--mismatch-weights",
        default=DEFAULT_MISMATCH_WEIGHTS,
        help=(
            "comma-separated mismatch_count:weight pairs applied independently "
            "to each mate (default: 0:0.50,1:0.30,2:0.10,3:0.10)"
        ),
    )
    parser.add_argument(
        "--max-occurrences",
        type=int,
        default=64,
        help=(
            "discard candidate fragments with more than this many exact genomic "
            "occurrences to avoid pathological repeats (default: 64)"
        ),
    )
    parser.add_argument(
        "--exclude-within-genome-repeats",
        action="store_true",
        help=(
            "exclude candidate inserts with multiple exact loci confined to a "
            "single genome; genuine cross-genome multimappers are retained"
        ),
    )
    parser.add_argument(
        "--exclude-cross-genome-multimappers",
        action="store_true",
        help=(
            "exclude candidate inserts whose exact occurrences span multiple "
            "genomes; useful for strict no-sharing control simulations"
        ),
    )
    return parser.parse_args(argv)


def read_single_fasta(path: Path) -> tuple[str, str]:
    """Read a FASTA file that must contain exactly one sequence.

    Parameters
    ----------
    path
        FASTA file path.

    Returns
    -------
    tuple
        ``(record_name, uppercase_sequence)``.

    Raises
    ------
    ValueError
        If the FASTA contains zero or multiple records, or non-ACGT sequence.
    """

    name: str | None = None
    sequence_parts: list[str] = []
    records = 0

    with path.open("r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.strip()
            if not line:
                continue
            if line.startswith(">"):
                records += 1
                if records > 1:
                    raise ValueError(f"Expected one FASTA record in {path}")
                name = line[1:].split()[0]
            else:
                if records == 0:
                    raise ValueError(f"Sequence encountered before FASTA header in {path}")
                sequence_parts.append(line.upper())

    if records != 1 or name is None:
        raise ValueError(f"Expected exactly one FASTA record in {path}")

    sequence = "".join(sequence_parts)
    bad = sorted(set(sequence) - set(DNA_BASES))
    if bad:
        raise ValueError(f"Non-ACGT bases in {path}: {''.join(bad)}")
    return name, sequence


def resolve_fasta_path(report_path: Path, raw_path: str, assembly: str) -> Path:
    """Resolve a chromosome FASTA path recorded by ``prepare_genomes.py``.

    The preparation script may have been run from a different working directory,
    so this helper tries the recorded path, a path relative to the validation
    report, and the conventional ``chromosomes/<assembly>.fna`` location.
    """

    candidates = [
        Path(raw_path),
        report_path.parent / raw_path,
        report_path.parent / "chromosomes" / f"{assembly}.fna",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate.resolve()
    joined = "\n  ".join(str(p) for p in candidates)
    raise FileNotFoundError(
        f"Could not locate FASTA for {assembly}; tried:\n  {joined}"
    )


def read_validated_genomes(path: Path) -> list[Genome]:
    """Load and verify validated chromosome metadata and FASTA sequences."""

    genomes: list[Genome] = []
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames is None:
            raise ValueError(f"Missing header in {path}")
        missing = REQUIRED_GENOME_COLUMNS - set(reader.fieldnames)
        if missing:
            raise ValueError(
                f"{path} is missing required columns: {', '.join(sorted(missing))}"
            )

        seen_assemblies: set[str] = set()
        seen_refs: set[str] = set()

        for row in reader:
            assembly = row["assembly_accession"].strip()
            if not assembly:
                continue
            if row["status"].strip().upper() != "PASS":
                raise ValueError(
                    f"Genome {assembly} is not PASS in {path}: {row['status']}"
                )
            if assembly in seen_assemblies:
                raise ValueError(f"Duplicate assembly in {path}: {assembly}")

            fasta = resolve_fasta_path(path, row["fasta_path"].strip(), assembly)
            fasta_name, sequence = read_single_fasta(fasta)
            chromosome_accession = row["chromosome_accession"].strip()
            if fasta_name != chromosome_accession:
                raise ValueError(
                    f"{assembly}: FASTA record {fasta_name!r} differs from "
                    f"validated chromosome accession {chromosome_accession!r}"
                )

            expected_length = int(row["chromosome_length"])
            if len(sequence) != expected_length:
                raise ValueError(
                    f"{assembly}: FASTA length {len(sequence)} differs from "
                    f"validated length {expected_length}"
                )
            if chromosome_accession in seen_refs:
                raise ValueError(
                    f"Duplicate chromosome reference accession: {chromosome_accession}"
                )

            genomes.append(
                Genome(
                    assembly_accession=assembly,
                    species=row["expected_species"].strip(),
                    strain=row["expected_strain"].strip(),
                    chromosome_accession=chromosome_accession,
                    sequence=sequence,
                    fasta_path=fasta,
                )
            )
            seen_assemblies.add(assembly)
            seen_refs.add(chromosome_accession)

    if not genomes:
        raise ValueError(f"No validated genomes found in {path}")
    return genomes


def read_abundances(path: Path, genomes: Sequence[Genome]) -> dict[str, float]:
    """Read true cell relative abundances and ensure exact genome coverage."""

    values: dict[str, float] = {}
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames is None:
            raise ValueError(f"Missing header in {path}")
        missing = REQUIRED_ABUNDANCE_COLUMNS - set(reader.fieldnames)
        if missing:
            raise ValueError(
                f"{path} is missing required columns: {', '.join(sorted(missing))}"
            )
        for row in reader:
            assembly = row["assembly_accession"].strip()
            if not assembly:
                continue
            if assembly in values:
                raise ValueError(f"Duplicate abundance entry: {assembly}")
            value = float(row["relative_abundance"])
            if not math.isfinite(value) or value < 0:
                raise ValueError(
                    f"Abundance for {assembly} must be finite and >= 0; got {value}"
                )
            values[assembly] = value

    expected = {g.assembly_accession for g in genomes}
    observed = set(values)
    if observed != expected:
        missing = sorted(expected - observed)
        extra = sorted(observed - expected)
        details = []
        if missing:
            details.append(f"missing: {', '.join(missing)}")
        if extra:
            details.append(f"unexpected: {', '.join(extra)}")
        raise ValueError("Abundance/genome mismatch (" + "; ".join(details) + ")")

    total = sum(values.values())
    if not math.isclose(total, 1.0, rel_tol=0.0, abs_tol=1e-8):
        raise ValueError(f"Relative abundances must sum to 1; observed {total:.12g}")
    return values


def parse_mismatch_weights(text: str) -> tuple[list[int], list[float]]:
    """Parse and validate the mismatch-class probability specification."""

    parsed: dict[int, float] = {}
    for token in text.split(","):
        token = token.strip()
        if not token:
            continue
        try:
            left, right = token.split(":", 1)
            mismatches = int(left)
            weight = float(right)
        except ValueError as exc:
            raise ValueError(
                f"Invalid --mismatch-weights token {token!r}; expected n:weight"
            ) from exc

        if mismatches < 0 or mismatches > 3:
            raise ValueError("Tier-2 mismatch counts must be in {0,1,2,3}")
        if not math.isfinite(weight) or weight < 0:
            raise ValueError("Mismatch weights must be finite and >= 0")
        if mismatches in parsed:
            raise ValueError(f"Duplicate mismatch class: {mismatches}")
        parsed[mismatches] = weight

    if not parsed or sum(parsed.values()) <= 0:
        raise ValueError("At least one positive mismatch weight is required")

    counts = sorted(parsed)
    weights = [parsed[n] for n in counts]
    return counts, weights


def safe_feature_id(text: str) -> str:
    """Convert a human-readable label to a stable whitespace-free feature ID."""

    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", text.strip())
    cleaned = cleaned.strip("_")
    return cleaned or "unnamed"


def reverse_complement(sequence: str) -> str:
    """Return the reverse complement of an A/C/G/T sequence."""

    return sequence.translate(COMPLEMENT)[::-1]


def encode_dna(sequence: str) -> int:
    """Encode an A/C/G/T sequence as a collision-free 2-bit integer."""

    code = 0
    for base in sequence:
        code <<= 2
        if base == "C":
            code |= 1
        elif base == "G":
            code |= 2
        elif base == "T":
            code |= 3
        elif base != "A":
            raise ValueError(f"Cannot encode non-ACGT base {base!r}")
    return code


def reverse_complement_code(code: int, k: int) -> int:
    """Return the 2-bit code of the reverse complement without a string."""

    rc = 0
    value = code
    for _ in range(k):
        base = value & 3
        rc = (rc << 2) | (3 - base)
        value >>= 2
    return rc


def rolling_kmer_codes(sequence: str, k: int) -> Iterator[tuple[int, int]]:
    """Yield ``(zero_based_start, code)`` for every k-mer in an ACGT sequence.

    A rolling 2-bit integer avoids allocating a new Python substring at every
    chromosome position, which is important when scanning tens of megabases.
    """

    if len(sequence) < k:
        return
    mask = (1 << (2 * k)) - 1
    code = encode_dna(sequence[:k])
    yield 0, code
    for i in range(k, len(sequence)):
        base = sequence[i]
        value = 0 if base == "A" else 1 if base == "C" else 2 if base == "G" else 3
        code = ((code << 2) | value) & mask
        yield i - k + 1, code


def largest_remainder_counts(
    probabilities: dict[str, float], total: int
) -> dict[str, int]:
    """Allocate an integer total while preserving probabilities as closely as possible."""

    exact = {key: probabilities[key] * total for key in probabilities}
    counts = {key: int(math.floor(value)) for key, value in exact.items()}
    remaining = total - sum(counts.values())

    # Stable lexical tie-breaking makes the allocation reproducible.
    order = sorted(
        probabilities,
        key=lambda key: (-(exact[key] - counts[key]), key),
    )
    for key in order[:remaining]:
        counts[key] += 1
    return counts


def sample_candidates(
    genomes: Sequence[Genome],
    requested_counts: dict[str, int],
    candidate_multiplier: float,
    rng: random.Random,
) -> list[Candidate]:
    """Sample an oversupply of source inserts for later shared-locus selection."""

    candidates: list[Candidate] = []
    for genome in genomes:
        needed = requested_counts[genome.assembly_accession]
        if needed == 0:
            continue
        max_start = genome.length - INSERT_LENGTH
        if max_start < 0:
            raise ValueError(
                f"Chromosome {genome.chromosome_accession} is shorter than insert length"
            )

        target = max(needed, int(math.ceil(needed * candidate_multiplier)))
        available = max_start + 1
        target = min(target, available)
        starts = rng.sample(range(available), target)

        for start in starts:
            fragment = genome.sequence[start : start + INSERT_LENGTH]
            candidates.append(
                Candidate(
                    source_assembly=genome.assembly_accession,
                    source_start=start,
                    fragment_code=encode_dna(fragment),
                )
            )
    return candidates


def find_exact_occurrences(
    genomes: Sequence[Genome],
    fragment_codes: Iterable[int],
) -> dict[int, list[Occurrence]]:
    """Find all forward and reverse-complement occurrences of candidate inserts.

    Only candidate fragment codes are indexed. Each chromosome is scanned once.
    This avoids constructing a genome-wide dictionary of every 175-mer.
    """

    wanted = set(fragment_codes)
    reverse_to_forward: dict[int, set[int]] = defaultdict(set)
    for code in wanted:
        reverse_to_forward[reverse_complement_code(code, INSERT_LENGTH)].add(code)

    occurrences: dict[int, set[Occurrence]] = {code: set() for code in wanted}

    for genome in genomes:
        print(
            f"  scanning {genome.assembly_accession} "
            f"({genome.length:,} bp) for candidate insert matches...",
            file=sys.stderr,
        )
        for start, code in rolling_kmer_codes(genome.sequence, INSERT_LENGTH):
            if code in wanted:
                occurrences[code].add(
                    Occurrence(genome.assembly_accession, start, "+")
                )
            rc_sources = reverse_to_forward.get(code)
            if rc_sources:
                for source_code in rc_sources:
                    occurrences[source_code].add(
                        Occurrence(genome.assembly_accession, start, "-")
                    )

    return {
        code: sorted(
            hits,
            key=lambda hit: (hit.assembly_accession, hit.start, hit.orientation),
        )
        for code, hits in occurrences.items()
    }


def choose_final_candidates(
    candidates: Sequence[Candidate],
    occurrences: dict[int, list[Occurrence]],
    requested_counts: dict[str, int],
    shared_fraction: float,
    max_occurrences: int,
    exclude_within_genome_repeats: bool,
    exclude_cross_genome_multimappers: bool,
    rng: random.Random,
) -> list[tuple[Candidate, list[Occurrence], str]]:
    """Select the final source inserts with controlled shared-locus enrichment."""

    by_source: dict[str, list[Candidate]] = defaultdict(list)
    for candidate in candidates:
        by_source[candidate.source_assembly].append(candidate)

    selected: list[tuple[Candidate, list[Occurrence], str]] = []

    for assembly in sorted(requested_counts):
        needed = requested_counts[assembly]
        if needed == 0:
            continue

        valid: list[tuple[Candidate, list[Occurrence], bool]] = []
        for candidate in by_source[assembly]:
            hits = occurrences.get(candidate.fragment_code, [])
            if not hits or len(hits) > max_occurrences:
                continue

            # The exact source location must always be represented.
            if Occurrence(assembly, candidate.source_start, "+") not in hits:
                raise RuntimeError(
                    f"Internal error: source occurrence missing for "
                    f"{assembly}:{candidate.source_start}"
                )
            target_assemblies = {hit.assembly_accession for hit in hits}

            # Optional sensitivity mode: remove inserts that occur at multiple
            # loci but only within one genome. Cross-genome ambiguity is kept.
            if (
                exclude_within_genome_repeats
                and len(hits) > 1
                and len(target_assemblies) == 1
            ):
                continue

            if (
                exclude_cross_genome_multimappers
                and len(target_assemblies) > 1
            ):
                continue

            valid.append((candidate, hits, len(target_assemblies) > 1))

        shared = [(c, h) for c, h, is_shared in valid if is_shared]
        unique = [(c, h) for c, h, is_shared in valid if not is_shared]

        # Sort before shuffle so the RNG, not hash/container ordering, controls
        # reproducibility.
        shared.sort(key=lambda x: (x[0].source_start, x[0].fragment_code))
        unique.sort(key=lambda x: (x[0].source_start, x[0].fragment_code))
        rng.shuffle(shared)
        rng.shuffle(unique)

        target_shared = int(round(needed * shared_fraction))
        take_shared = min(target_shared, len(shared))
        chosen_shared = shared[:take_shared]

        remaining = needed - len(chosen_shared)
        chosen_unique = unique[:remaining]
        remaining -= len(chosen_unique)

        # If one category is insufficient, fill from unused shared candidates.
        # This preserves the requested total without fabricating loci.
        fill_shared = shared[take_shared : take_shared + remaining]
        remaining -= len(fill_shared)

        if remaining:
            raise RuntimeError(
                f"Not enough valid candidates for {assembly}: need {needed}, "
                f"available {len(valid)} after repeat filtering. Increase "
                f"--candidate-multiplier or --max-occurrences."
            )

        for candidate, hits in chosen_shared:
            selected.append((candidate, hits, "enriched_shared"))
        for candidate, hits in chosen_unique:
            selected.append((candidate, hits, "ordinary_unique"))
        for candidate, hits in fill_shared:
            selected.append((candidate, hits, "shared_fill"))

        print(
            f"  {assembly}: selected {needed:,} inserts "
            f"({len(chosen_shared) + len(fill_shared):,} shared across genomes)",
            file=sys.stderr,
        )

    return selected


def mutate_read(sequence: str, n_mismatches: int, rng: random.Random) -> str:
    """Introduce exactly ``n_mismatches`` substitutions at distinct positions."""

    if n_mismatches == 0:
        return sequence
    if n_mismatches > len(sequence):
        raise ValueError("Mismatch count exceeds read length")

    chars = list(sequence)
    for pos in sorted(rng.sample(range(len(sequence)), n_mismatches)):
        original = chars[pos]
        alternatives = [base for base in DNA_BASES if base != original]
        chars[pos] = rng.choice(alternatives)
    return "".join(chars)


def md_tag(reference: str, query_aligned: str) -> tuple[str, int]:
    """Construct an MD tag and mismatch count for a mismatch-only alignment."""

    if len(reference) != len(query_aligned):
        raise ValueError("Reference/query length mismatch when constructing MD tag")

    pieces: list[str] = []
    matches = 0
    mismatches = 0
    for ref_base, query_base in zip(reference, query_aligned):
        if ref_base == query_base:
            matches += 1
        else:
            pieces.append(str(matches))
            pieces.append(ref_base)
            matches = 0
            mismatches += 1
    pieces.append(str(matches))
    return "".join(pieces), mismatches


def choose_mismatch_count(
    counts: Sequence[int], weights: Sequence[float], rng: random.Random
) -> int:
    """Draw one mismatch count according to configured weights."""

    return rng.choices(counts, weights=weights, k=1)[0]


def occurrence_geometry(
    occurrence: Occurrence, mate: int
) -> tuple[int, bool, int, bool, int]:
    """Return alignment geometry for one mate at an exact 175-bp occurrence.

    Returns
    -------
    tuple
        ``(start0, reverse, mate_start0, mate_reverse, template_length)``.
    """

    p = occurrence.start
    if occurrence.orientation == "+":
        if mate == 1:
            return p, False, p + MATE_OFFSET, True, INSERT_LENGTH
        return p + MATE_OFFSET, True, p, False, -INSERT_LENGTH

    # Reverse occurrence: mate 2 is leftmost/forward, mate 1 rightmost/reverse.
    if mate == 1:
        return p + MATE_OFFSET, True, p, False, -INSERT_LENGTH
    return p, False, p + MATE_OFFSET, True, INSERT_LENGTH


def sam_sequence_for_alignment(original_read: str, reverse: bool) -> str:
    """Return SAM SEQ in reference-aligned orientation for the FLAG strand."""

    return reverse_complement(original_read) if reverse else original_read


def build_flag(
    mate: int,
    reverse: bool,
    mate_reverse: bool,
    secondary: bool,
    mate_present: bool,
) -> int:
    """Construct a conventional paired-end SAM FLAG for this synthetic record."""

    flag = 0x1  # paired
    flag |= 0x40 if mate == 1 else 0x80

    if reverse:
        flag |= 0x10

    if mate_present:
        flag |= 0x2  # proper pair
        if mate_reverse:
            flag |= 0x20
    else:
        flag |= 0x8  # mate unmapped/absent

    if secondary:
        flag |= 0x100
    return flag


def write_sam_and_truth(
    output_dir: Path,
    genomes: Sequence[Genome],
    selected: list[SelectedInsert],
    genome_by_assembly: dict[str, Genome],
    mismatch_counts: Sequence[int],
    mismatch_weights: Sequence[float],
    rng: random.Random,
) -> Counter:
    """Generate SAM and minimal source truth, asserting emitted targets match simulator truth."""

    sam_path = output_dir / "alignments.sam"
    insert_sources_path = output_dir / "insert_sources.tsv"

    stats: Counter = Counter()

    with (
        sam_path.open("w", encoding="utf-8", newline="\n") as sam,
        insert_sources_path.open("w", encoding="utf-8", newline="") as inserts_file,
    ):
        # Query-name grouping is intentional and documented in the header.
        sam.write("@HD\tVN:1.6\tSO:queryname\n")
        for genome in genomes:
            sam.write(
                f"@SQ\tSN:{genome.chromosome_accession}\tLN:{genome.length}\n"
            )
        sam.write(
            "@CO\tSynthetic msamtools Tier-2 validation data: "
            "2x100 bp, 175-bp inserts, CIGAR 100M, substitutions only\n"
        )

        insert_fields = [
            "qname",
            "source_assembly",
            "mate_status",
        ]
        insert_writer = csv.DictWriter(
            inserts_file, fieldnames=insert_fields, delimiter="\t", lineterminator="\n"
        )
        insert_writer.writeheader()

        for insert in selected:
            source = genome_by_assembly[insert.source_assembly]
            fragment = source.sequence[
                insert.source_start : insert.source_start + INSERT_LENGTH
            ]

            # Biological read sequences before SAM strand representation.
            mate1_original = fragment[:READ_LENGTH]
            mate2_original = reverse_complement(fragment[-READ_LENGTH:])

            insert.mate1_nm = choose_mismatch_count(
                mismatch_counts, mismatch_weights, rng
            )
            insert.mate2_nm = choose_mismatch_count(
                mismatch_counts, mismatch_weights, rng
            )
            mate1_read = mutate_read(mate1_original, insert.mate1_nm, rng)
            mate2_read = mutate_read(mate2_original, insert.mate2_nm, rng)

            target_assemblies = sorted(
                {hit.assembly_accession for hit in insert.occurrences}
            )

            # Single-mate inserts intentionally isolate insert-space counting:
            # only the source occurrence of the surviving mate is emitted.
            if insert.mate_status == "r1_only":
                records_to_emit = [
                    (Occurrence(insert.source_assembly, insert.source_start, "+"), 1)
                ]
            elif insert.mate_status == "r2_only":
                records_to_emit = [
                    (Occurrence(insert.source_assembly, insert.source_start, "+"), 2)
                ]
            else:
                records_to_emit = [
                    (hit, mate)
                    for hit in insert.occurrences
                    for mate in (1, 2)
                ]

            # Track the target assemblies represented in the actual SAM
            # records for this QNAME. Simulator truth remains defined by the
            # exact-occurrence model; this only verifies that SAM emission has
            # preserved that truth.
            emitted_target_assemblies: set[str] = set()

            for hit, mate in records_to_emit:
                emitted_target_assemblies.add(hit.assembly_accession)
                target = genome_by_assembly[hit.assembly_accession]
                source_occurrence = (
                    hit.assembly_accession == insert.source_assembly
                    and hit.start == insert.source_start
                    and hit.orientation == "+"
                )
                # The original source pair is primary. Alternative exact
                # occurrences are secondary; profile intentionally ignores this flag.
                secondary = not source_occurrence

                if insert.mate_status == "both_mapped":
                    start0, reverse, mate_start0, mate_reverse, tlen = (
                        occurrence_geometry(hit, mate)
                    )
                    mate_present = True
                    rnext = "="
                    pnext = mate_start0 + 1
                else:
                    start0, reverse, _, _, _ = occurrence_geometry(hit, mate)
                    mate_reverse = False
                    tlen = 0
                    mate_present = False
                    rnext = "*"
                    pnext = 0

                original_query = mate1_read if mate == 1 else mate2_read
                seq = sam_sequence_for_alignment(original_query, reverse)
                reference = target.sequence[start0 : start0 + READ_LENGTH]
                md, observed_nm = md_tag(reference, seq)
                expected_nm = insert.mate1_nm if mate == 1 else insert.mate2_nm
                if observed_nm != expected_nm:
                    raise RuntimeError(
                        f"Internal mismatch inconsistency for {insert.qname}/"
                        f"{mate} at {target.chromosome_accession}:{start0 + 1}: "
                        f"expected NM={expected_nm}, observed {observed_nm}"
                    )

                # +1 for match and -1 for mismatch -> AS = 100 - 2*NM.
                as_score = READ_LENGTH - 2 * observed_nm
                flag = build_flag(
                    mate=mate,
                    reverse=reverse,
                    mate_reverse=mate_reverse,
                    secondary=secondary,
                    mate_present=mate_present,
                )

                sam.write(
                    "\t".join(
                        [
                            insert.qname,
                            str(flag),
                            target.chromosome_accession,
                            str(start0 + 1),
                            "255",
                            f"{READ_LENGTH}M",
                            rnext,
                            str(pnext),
                            str(tlen),
                            seq,
                            "I" * READ_LENGTH,
                            f"NM:i:{observed_nm}",
                            f"MD:Z:{md}",
                            f"AS:i:{as_score}",
                        ]
                    )
                    + "\n"
                )


            expected_target_assemblies = (
                {insert.source_assembly}
                if insert.mate_status != "both_mapped"
                else {hit.assembly_accession for hit in insert.occurrences}
            )
            if emitted_target_assemblies != expected_target_assemblies:
                raise RuntimeError(
                    f"Internal SAM consistency error for {insert.qname}: "
                    f"expected target assemblies "
                    f"{sorted(expected_target_assemblies)}, emitted "
                    f"{sorted(emitted_target_assemblies)}"
                )

            insert_writer.writerow(
                {
                    "qname": insert.qname,
                    "source_assembly": source.assembly_accession,
                    "mate_status": insert.mate_status,
                }
            )

            stats["inserts"] += 1
            stats[f"mate_status:{insert.mate_status}"] += 1
            stats[f"selection_mode:{insert.selection_mode}"] += 1
            stats[f"mate1_nm:{insert.mate1_nm}"] += 1
            stats[f"mate2_nm:{insert.mate2_nm}"] += 1
            if len(target_assemblies) > 1:
                stats["cross_genome_multimappers"] += 1
            else:
                stats["single_genome_inserts"] += 1

    stats["sam_alignment_records"] = sum(
        1
        for item in selected
        for _ in (
            [1]
            if item.mate_status != "both_mapped"
            else [None] * (2 * len(item.occurrences))
        )
    )
    return stats


def write_reference_files(output_dir: Path, genomes: Sequence[Genome]) -> None:
    """Write reference metadata and msamtools species/strain definition files."""

    metadata_path = output_dir / "reference_metadata.tsv"
    species_path = output_dir / "reference_to_species.tsv"
    strain_path = output_dir / "reference_to_strain.tsv"

    with (
        metadata_path.open("w", encoding="utf-8", newline="") as metadata,
        species_path.open("w", encoding="utf-8", newline="") as species_file,
        strain_path.open("w", encoding="utf-8", newline="") as strain_file,
    ):
        fields = [
            "reference",
            "assembly_accession",
            "species",
            "strain",
            "species_feature_id",
            "strain_feature_id",
            "chromosome_length",
        ]
        writer = csv.DictWriter(
            metadata, fieldnames=fields, delimiter="\t", lineterminator="\n"
        )
        writer.writeheader()

        for genome in genomes:
            species_id = safe_feature_id(genome.species)
            strain_id = safe_feature_id(
                f"{genome.species}__{genome.strain}__{genome.assembly_accession}"
            )
            writer.writerow(
                {
                    "reference": genome.chromosome_accession,
                    "assembly_accession": genome.assembly_accession,
                    "species": genome.species,
                    "strain": genome.strain,
                    "species_feature_id": species_id,
                    "strain_feature_id": strain_id,
                    "chromosome_length": genome.length,
                }
            )
            species_file.write(f"{species_id}\t{genome.chromosome_accession}\n")
            strain_file.write(f"{strain_id}\t{genome.chromosome_accession}\n")


def write_community_truth(
    output_dir: Path,
    genomes: Sequence[Genome],
    cell_abundance: dict[str, float],
    dna_fraction: dict[str, float],
    requested_counts: dict[str, int],
    selected: Sequence[SelectedInsert],
) -> None:
    """Write biological truth and realized source-insert counts."""

    realized = Counter(item.source_assembly for item in selected)
    path = output_dir / "community_truth.tsv"
    fields = [
        "assembly_accession",
        "reference",
        "species",
        "strain",
        "chromosome_length",
        "true_cell_relative_abundance",
        "expected_dna_fraction",
        "requested_source_inserts",
        "realized_source_inserts",
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=fields, delimiter="\t", lineterminator="\n"
        )
        writer.writeheader()
        for genome in genomes:
            assembly = genome.assembly_accession
            writer.writerow(
                {
                    "assembly_accession": assembly,
                    "reference": genome.chromosome_accession,
                    "species": genome.species,
                    "strain": genome.strain,
                    "chromosome_length": genome.length,
                    "true_cell_relative_abundance": f"{cell_abundance[assembly]:.12g}",
                    "expected_dna_fraction": f"{dna_fraction[assembly]:.12g}",
                    "requested_source_inserts": requested_counts[assembly],
                    "realized_source_inserts": realized[assembly],
                }
            )



def write_multimapping_pairs(
    output_dir: Path,
    selected: Sequence[SelectedInsert],
    genome_by_assembly: dict[str, Genome],
) -> Counter:
    """Write cross-genome ambiguity pair counts and return ambiguity statistics.

    The simulator distinguishes three insert-level mapping classes:

    * ``single_locus_single_genome``: exactly one 175-bp occurrence.
    * ``multiple_loci_single_genome``: repeated locus/loci, but all occurrences
      belong to the same genome.
    * ``multiple_genomes``: occurrences span two or more genomes.

    ``multimapping_pairs.tsv`` reports all unordered target-genome pairs for the
    third class. Inserts mapping to three or more genomes contribute once to
    each pair, so pair counts are descriptive and need not sum to the number of
    cross-genome multi-mapped inserts.
    """

    stats: Counter = Counter()
    pair_counts: Counter = Counter()

    for item in selected:
        n_occurrences = len(item.occurrences)
        target_assemblies = sorted(
            {hit.assembly_accession for hit in item.occurrences}
        )

        if n_occurrences == 1:
            stats["single_locus_single_genome"] += 1
        elif len(target_assemblies) == 1:
            stats["multiple_loci_single_genome"] += 1
        else:
            stats["multiple_genomes"] += 1
            for left, right in combinations(target_assemblies, 2):
                pair_counts[(left, right)] += 1

    path = output_dir / "multimapping_pairs.tsv"
    fields = [
        "assembly_a",
        "species_a",
        "strain_a",
        "assembly_b",
        "species_b",
        "strain_b",
        "n_inserts",
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=fields, delimiter="\t", lineterminator="\n"
        )
        writer.writeheader()
        for (left, right), count in sorted(
            pair_counts.items(), key=lambda item: (-item[1], item[0])
        ):
            genome_a = genome_by_assembly[left]
            genome_b = genome_by_assembly[right]
            writer.writerow(
                {
                    "assembly_a": left,
                    "species_a": genome_a.species,
                    "strain_a": genome_a.strain,
                    "assembly_b": right,
                    "species_b": genome_b.species,
                    "strain_b": genome_b.strain,
                    "n_inserts": count,
                }
            )

    return stats

def write_summary(
    output_dir: Path,
    args: argparse.Namespace,
    genomes: Sequence[Genome],
    stats: Counter,
    selected: Sequence[SelectedInsert],
    ambiguity_stats: Counter,
) -> None:
    """Write machine-readable simulation summary and print a concise report."""

    shared = sum(
        1
        for item in selected
        if len({h.assembly_accession for h in item.occurrences}) > 1
    )
    single_mate = sum(1 for item in selected if item.mate_status != "both_mapped")

    summary = [
        ("seed", args.seed),
        ("num_genomes", len(genomes)),
        ("requested_inserts", args.num_inserts),
        ("realized_inserts", stats["inserts"]),
        ("sam_alignment_records", stats["sam_alignment_records"]),
        ("read_length", READ_LENGTH),
        ("insert_length", INSERT_LENGTH),
        ("mate_overlap", 2 * READ_LENGTH - INSERT_LENGTH),
        ("target_shared_fraction", args.shared_fraction),
        ("realized_cross_genome_multimapper_inserts", shared),
        (
            "realized_cross_genome_multimapper_fraction",
            shared / args.num_inserts if args.num_inserts else 0,
        ),
        ("single_locus_single_genome_inserts", ambiguity_stats["single_locus_single_genome"]),
        ("multiple_loci_single_genome_inserts", ambiguity_stats["multiple_loci_single_genome"]),
        ("multiple_genomes_inserts", ambiguity_stats["multiple_genomes"]),
        ("target_single_mate_fraction", args.single_mate_fraction),
        ("realized_single_mate_inserts", single_mate),
        (
            "realized_single_mate_fraction",
            single_mate / args.num_inserts if args.num_inserts else 0,
        ),
        ("candidate_multiplier", args.candidate_multiplier),
        ("max_occurrences", args.max_occurrences),
        ("exclude_within_genome_repeats", int(args.exclude_within_genome_repeats)),
        ("exclude_cross_genome_multimappers", int(args.exclude_cross_genome_multimappers)),
        ("mismatch_weights", args.mismatch_weights),
    ]

    for key in sorted(k for k in stats if k.startswith("mate1_nm:")):
        summary.append((key, stats[key]))
    for key in sorted(k for k in stats if k.startswith("mate2_nm:")):
        summary.append((key, stats[key]))
    for key in sorted(k for k in stats if k.startswith("selection_mode:")):
        summary.append((key, stats[key]))

    path = output_dir / "simulation_summary.tsv"
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(["metric", "value"])
        writer.writerows(summary)

    print("\nSynthetic validation dataset complete", file=sys.stderr)
    print("-------------------------------------", file=sys.stderr)
    print(f"Genomes:                    {len(genomes):,}", file=sys.stderr)
    print(f"Inserts:                    {args.num_inserts:,}", file=sys.stderr)
    print(
        f"Cross-genome multimappers:  {shared:,} "
        f"({100 * shared / args.num_inserts:.2f}%)",
        file=sys.stderr,
    )
    print(
        f"Repeated loci, one genome:  "
        f"{ambiguity_stats['multiple_loci_single_genome']:,}",
        file=sys.stderr,
    )
    print(
        f"Single-mate inserts:        {single_mate:,} "
        f"({100 * single_mate / args.num_inserts:.2f}%)",
        file=sys.stderr,
    )
    print(
        f"SAM alignment records:      {stats['sam_alignment_records']:,}",
        file=sys.stderr,
    )
    print(f"Output directory:           {output_dir}", file=sys.stderr)


def assign_single_mate_cases(
    selected: list[SelectedInsert],
    fraction: float,
    rng: random.Random,
) -> None:
    """Mark a controlled subset of non-shared inserts as R1-only or R2-only.

    Preference is given to ordinary single-genome inserts so this validation
    feature tests insert-space counting without conflating it with multimapping.
    """

    n_target = int(round(len(selected) * fraction))
    if n_target == 0:
        return

    preferred = [
        i
        for i, item in enumerate(selected)
        if len({h.assembly_accession for h in item.occurrences}) == 1
    ]
    fallback = [i for i in range(len(selected)) if i not in set(preferred)]

    preferred.sort()
    fallback.sort()
    rng.shuffle(preferred)
    rng.shuffle(fallback)
    chosen = (preferred + fallback)[:n_target]

    for index in chosen:
        selected[index].mate_status = rng.choice(["r1_only", "r2_only"])


def validate_numeric_args(args: argparse.Namespace) -> None:
    """Validate numeric command-line settings before expensive genome scanning."""

    if args.num_inserts <= 0:
        raise ValueError("--num-inserts must be > 0")
    if not (0 <= args.shared_fraction <= 1):
        raise ValueError("--shared-fraction must be between 0 and 1")
    if not (0 <= args.single_mate_fraction <= 1):
        raise ValueError("--single-mate-fraction must be between 0 and 1")
    if args.candidate_multiplier < 1:
        raise ValueError("--candidate-multiplier must be >= 1")
    if args.max_occurrences < 1:
        raise ValueError("--max-occurrences must be >= 1")


def main(argv: list[str] | None = None) -> int:
    """Run the synthetic validation-data generator."""

    args = parse_args(argv)
    try:
        validate_numeric_args(args)
        mismatch_counts, mismatch_weights = parse_mismatch_weights(
            args.mismatch_weights
        )

        print("Loading validated chromosomes...", file=sys.stderr)
        genomes = read_validated_genomes(args.validated_genomes)
        genome_by_assembly = {g.assembly_accession: g for g in genomes}
        cell_abundance = read_abundances(args.abundances, genomes)

        # Shotgun DNA sampling probability is abundance x chromosome length.
        dna_weights = {
            g.assembly_accession: cell_abundance[g.assembly_accession] * g.length
            for g in genomes
        }
        weight_sum = sum(dna_weights.values())
        dna_fraction = {key: value / weight_sum for key, value in dna_weights.items()}
        requested_counts = largest_remainder_counts(
            dna_fraction, args.num_inserts
        )

        rng = random.Random(args.seed)
        args.output_dir.mkdir(parents=True, exist_ok=True)

        print(
            f"Sampling candidate inserts "
            f"(multiplier={args.candidate_multiplier:g})...",
            file=sys.stderr,
        )
        candidates = sample_candidates(
            genomes, requested_counts, args.candidate_multiplier, rng
        )
        print(
            f"Candidate inserts: {len(candidates):,}; "
            f"unique fragment codes: {len({c.fragment_code for c in candidates}):,}",
            file=sys.stderr,
        )

        print("Finding exact 175-bp occurrences across chromosomes...", file=sys.stderr)
        occurrences = find_exact_occurrences(
            genomes, (c.fragment_code for c in candidates)
        )

        print("Selecting final source inserts...", file=sys.stderr)
        chosen = choose_final_candidates(
            candidates=candidates,
            occurrences=occurrences,
            requested_counts=requested_counts,
            shared_fraction=args.shared_fraction,
            max_occurrences=args.max_occurrences,
            exclude_within_genome_repeats=args.exclude_within_genome_repeats,
            exclude_cross_genome_multimappers=args.exclude_cross_genome_multimappers,
            rng=rng,
        )

        # Stable source/order layout, then sequential QNAME assignment.
        chosen.sort(
            key=lambda item: (
                item[0].source_assembly,
                item[0].source_start,
                item[2],
            )
        )
        selected = [
            SelectedInsert(
                qname=f"sim{index:08d}",
                source_assembly=candidate.source_assembly,
                source_start=candidate.source_start,
                fragment_code=candidate.fragment_code,
                occurrences=hits,
                selection_mode=mode,
            )
            for index, (candidate, hits, mode) in enumerate(chosen, start=1)
        ]

        assign_single_mate_cases(selected, args.single_mate_fraction, rng)

        write_reference_files(args.output_dir, genomes)
        write_community_truth(
            args.output_dir,
            genomes,
            cell_abundance,
            dna_fraction,
            requested_counts,
            selected,
        )
        stats = write_sam_and_truth(
            args.output_dir,
            genomes,
            selected,
            genome_by_assembly,
            mismatch_counts,
            mismatch_weights,
            rng,
        )
        ambiguity_stats = write_multimapping_pairs(
            args.output_dir, selected, genome_by_assembly
        )
        write_summary(
            args.output_dir, args, genomes, stats, selected, ambiguity_stats
        )
        return 0

    except (OSError, ValueError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
